"""empty message

Revision ID: 6f7a78c33d8a
Revises: e39cf440710d
Create Date: 2016-11-04 11:17:41.651365

"""

# revision identifiers, used by Alembic.
revision = '6f7a78c33d8a'
down_revision = 'e39cf440710d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_apps',
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_apps')
    ### end Alembic commands ###
