"""empty message

Revision ID: af70fb36aee9
Revises: e9f77bd78fbd
Create Date: 2016-10-31 16:47:12.498885

"""

# revision identifiers, used by Alembic.
revision = 'af70fb36aee9'
down_revision = 'e9f77bd78fbd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'interactionPoints')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('interactionPoints', mysql.VARCHAR(length=250), nullable=False))
    ### end Alembic commands ###
