"""empty message

Revision ID: d7a9382a02a2
Revises: 7ffee8e91f15
Create Date: 2016-10-27 16:52:41.413734

"""

# revision identifiers, used by Alembic.
revision = 'd7a9382a02a2'
down_revision = '7ffee8e91f15'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=250), nullable=False))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
