"""empty message

Revision ID: dc035f2fa235
Revises: None
Create Date: 2016-10-26 17:20:32.975298

"""

# revision identifiers, used by Alembic.
revision = 'dc035f2fa235'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApplicationTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('interactionPoints', sa.String(length=250), nullable=False),
    sa.Column('permission', sa.String(length=250), nullable=False),
    sa.Column('osVersion', sa.String(length=250), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('launchurl', sa.String(length=250), nullable=False),
    sa.Column('installscript', sa.String(length=250), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('uninstallscript', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['CategoryTable.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('launchurl'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applicationupdatetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updates', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ApplicationTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicationupdatetable')
    op.drop_table('ApplicationTable')
    ### end Alembic commands ###
