"""empty message

Revision ID: e39cf440710d
Revises: None
Create Date: 2016-11-02 15:41:40.256924

"""

# revision identifiers, used by Alembic.
revision = 'e39cf440710d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=250), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('developer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('website', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=250), nullable=False),
    sa.Column('osVersion', sa.String(length=250), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('launchurl', sa.String(length=250), nullable=False),
    sa.Column('application_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['developer_id'], ['developer.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('launchurl'),
    sa.UniqueConstraint('name')
    )
    op.create_table('applicationassets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=250), nullable=False),
    sa.Column('screenShotOne', sa.String(length=250), nullable=True),
    sa.Column('screenShotTwo', sa.String(length=250), nullable=True),
    sa.Column('screenShotThree', sa.String(length=250), nullable=True),
    sa.Column('screenShotFour', sa.String(length=250), nullable=True),
    sa.Column('video', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('icon'),
    sa.UniqueConstraint('screenShotFour'),
    sa.UniqueConstraint('screenShotOne'),
    sa.UniqueConstraint('screenShotThree'),
    sa.UniqueConstraint('screenShotTwo'),
    sa.UniqueConstraint('video')
    )
    op.create_table('applicationupdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updates', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicationupdates')
    op.drop_table('applicationassets')
    op.drop_table('application')
    op.drop_table('developer')
    op.drop_table('user')
    op.drop_table('category')
    ### end Alembic commands ###
