"""empty message

Revision ID: e9f77bd78fbd
Revises: 5457b45dd82e
Create Date: 2016-10-31 10:42:58.809051

"""

# revision identifiers, used by Alembic.
revision = 'e9f77bd78fbd'
down_revision = '5457b45dd82e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'installscript')
    op.drop_column('application', 'uninstallscript')
    op.add_column('category', sa.Column('description', sa.String(length=250), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'description')
    op.add_column('application', sa.Column('uninstallscript', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('application', sa.Column('installscript', mysql.VARCHAR(length=250), nullable=False))
    ### end Alembic commands ###
