"""empty message

Revision ID: 975fb056f198
Revises: d85a5a195958
Create Date: 2016-11-10 17:33:46.994380

"""

# revision identifiers, used by Alembic.
revision = '975fb056f198'
down_revision = 'd85a5a195958'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('uuid', sa.String(length=250), nullable=False))
    op.alter_column('applicationassets', 'screenShotFour',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('applicationassets', 'screenShotOne',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('applicationassets', 'screenShotThree',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('applicationassets', 'screenShotTwo',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('applicationassets', 'video',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.drop_index('icon', table_name='applicationassets')
    op.drop_index('screenShotFour', table_name='applicationassets')
    op.drop_index('screenShotOne', table_name='applicationassets')
    op.drop_index('screenShotThree', table_name='applicationassets')
    op.drop_index('screenShotTwo', table_name='applicationassets')
    op.drop_index('video', table_name='applicationassets')
    op.drop_constraint(u'applicationassets_ibfk_1', 'applicationassets', type_='foreignkey')
    op.create_foreign_key(None, 'applicationassets', 'application', ['application_id'], ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applicationassets', type_='foreignkey')
    op.create_foreign_key(u'applicationassets_ibfk_1', 'applicationassets', 'application', ['application_id'], ['id'])
    op.create_index('video', 'applicationassets', ['video'], unique=True)
    op.create_index('screenShotTwo', 'applicationassets', ['screenShotTwo'], unique=True)
    op.create_index('screenShotThree', 'applicationassets', ['screenShotThree'], unique=True)
    op.create_index('screenShotOne', 'applicationassets', ['screenShotOne'], unique=True)
    op.create_index('screenShotFour', 'applicationassets', ['screenShotFour'], unique=True)
    op.create_index('icon', 'applicationassets', ['icon'], unique=True)
    op.alter_column('applicationassets', 'video',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('applicationassets', 'screenShotTwo',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('applicationassets', 'screenShotThree',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('applicationassets', 'screenShotOne',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('applicationassets', 'screenShotFour',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.drop_column('application', 'uuid')
    ### end Alembic commands ###
